# .streamlit/secrets.toml
[connections.snowflake]
account=FHB45051
user=JPITTMAN2000
password=Yay123456
role=SYSADMIN
warehouse=COMPUTE_WH
database=SMOOTHIES
schema=PUBLIC
client_session_keep_alive=true
